config/routes.rb
Rails.application.routes.draw do
  #フォロー、フォロワー
  get 'relationships/followings'
  get 'relationships/followers'

  #検索
  get "search" => "searches#search"


  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  devise_for :users

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create,:destroy]
    resources :book_comments, only: [:create,:destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    resource :chat, only: [:show], controller: 'user_chats'
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

    belongs_to :user
    belongs_to :book

    validates :comment,presence:true,length:{maximum:200}
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book_comment = BookComment.new
    @book = Book.find(params[:book_id])
    @user = @book.user
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = @book.id
    comment.save

  end

  def destroy
    @book_comment = BookComment.new
    @comment = Book.find(params[:book_id])
    @user = @comment.user
    comment = @comment.book_comments.find(params[:id])
    if current_user.id == comment.user.id
    comment.destroy

    else
      render "books/show"
    end
  end

  def book_comment_params
      params.require(:book_comment).permit(:comment)
  end


end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_book_comments.html.erb
<table class='table'>
  <tr>
    <td><%= link_to(book.user) do %>
      <%= image_tag book.user.get_profile_image(50,50)%><br>
      <%= user.name %>

    </td>
    <td><%= link_to book.title, book %></td>
    <td><%= book.body %></td>



    <td id="favorite_buttons_<%= book.id %>">
    <%= render "favorites/favorite", book: book %>
    </td>



    <% end %>

    <td><p>コメント件数：<%= book.book_comments.count %></p></td>

    <% if book.user == current_user %>
      <td><%= link_to 'Edit', edit_book_path(book), class: "btn btn-sm btn-success" %></td>
      <td><%= link_to 'Destroy', book_path(book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
    <% end %>
  </tr>
</table>

<% book.book_comments.each do |book_comment| %>
<div>
<%= image_tag book_comment.user.get_profile_image(50,50) %>

<%= book_comment.comment %>

<% if book_comment.user == current_user %>
  <%= link_to 'Destroy', book_book_comment_path(book, book_comment.id), method: :delete, remote: true, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%>
<% end %>
<p><%= book_comment.user.name %></p>
</div>
<% end %>

<div>
  <%= form_with model:[book,book_comment],local:false do |f| %>
    <div class="form-group">
      <%= f.label :comment %>
      <%= f.text_area :comment, class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= f.submit '送信'%>
    </div>
  <% end %>
</div>

app/views/book_comments/create.js.erb
$('#book_comment_buttons_<%= @book.id %>').html("<%= j(render "book_comments/book_comments", {book: @book,book_comment: @book_comment,user: @user}) %>");

app/views/book_comments/destroy.js.erb
$('#book_comment_buttons_<%= @comment.id %>').html("<%= j(render "book_comments/book_comments", {book: @comment,book_comment: @book_comment,user: @user}) %>");